### ISSUE TITLE
ランダム関数が不完全

### ISSUE THREAD

**Issue by psephopaiktes** [psephopaiktes/CoC_Bookmarklet#1]
同時にランダム関数を実行しているため、能力値のうちのいくつかが必ず同じ値になってしまう。タイミングをずらすなどして重複しない値にする必要がある。

**Comment by neriwasabiseijin** [comment]
random(1~6)+random(1~6)+random(1~6)

**Comment by psephopaiktes** [comment]
@neriwasabiseijin そういう話ではなく、random関数は時間から計算してランダムに数値を出すので、同時に実行すると同じ値がでてしまう。例えば、APPとDEXがいっしょになっちゃうとか。SetInterval使って解決したわ

**Comment by psephopaiktes** [comment]
解決したはずなんだけど、わりと同じ数値でるなあ…

**Comment by neriwasabiseijin** [comment]
1から6のランダムを三回足すのは確率をサイコロに近づけるため。
SEED値がえらべないJSフ○ック。
無理矢理精度高める方法もあるらしい
http://outofmem.tumblr.com/post/75785092410/javascriptそこそこ精度の高い乱数を手に入れる
