### ISSUE TITLE
HP, MPが自動計算されない

### ISSUE THREAD

**Issue by psephopaiktes** [psephopaiktes/CoC_Bookmarklet#2]
手入力する場合と違って、JSで能力値を入力した場合HP,MPなどの値が計算・入力されない。公式のJS関数を発火させる必要がある。

**Comment by neriwasabiseijin** [comment]
calcNoryokuKihonchi()

**Comment by psephopaiktes** [comment]
@neriwasabiseijin それどうやってしらべるの。あとその関数consoleでうちこんでも動かない…

**Comment by neriwasabiseijin** [comment]
スクリプトの欄にあったでーただ、.minになってたからくそ探しづらい。

**Comment by psephopaiktes** [comment]
なるほど
