### ISSUE TITLE
技能値の出力

### ISSUE THREAD

**Issue by psephopaiktes** [psephopaiktes/CoC_Bookmarklet#3]
各種技能値のinput要素にはIDが振られていないため、eq()で取得する必要あがある。あと、初期値技能以外を取得したい。

**Comment by neriwasabiseijin** [comment]
select要素のonChange()呼んだら自動計算も含めてうまくいくんじゃね？？？

**Comment by psephopaiktes** [comment]
@neriwasabiseijin 
能力値じゃなくて技能値の話ね。selectじゃないよ。

**Comment by psephopaiktes** [comment]
onChangeってイベントとしてJS内でも発火できるの ?

**Comment by psephopaiktes** [comment]
http://qiita.com/foo9/items/51ffdaa5305fbc4efa58 これでいけたわ
